services:
  mysql:
    container_name: 'mysql-defensium'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=db_defensium'
      - 'MYSQL_PASSWORD=defensium'
      - 'MYSQL_ROOT_PASSWORD=defensium'
      - 'MYSQL_USER=defensium'
    ports:
      - '3306:3306'