-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE tb_categoria_credencial (
	code bigint NOT NULL,
	code_public varchar(255) NULL,
	data_criacao datetime(6) NULL,
	data_delecao datetime(6) NULL,
	data_edicao datetime(6) NULL,
	descricao varchar(255) NULL
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;