-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE tb_credencial (
	code bigint NOT NULL,
	active bit(1) NULL,
	code_public varchar(255) NULL,
	data_criacao datetime(6) NULL,
	data_delecao datetime(6) NULL,
	data_edicao datetime(6) NULL,
	descricao varchar(255) NULL,
	identificador varchar(255) NULL,
	link varchar(255) NULL,
	observacao varchar(255) NULL,
	senha varchar(255) NULL,
	id_categoria_credencial bigint NULL,
	id_pessoa bigint NULL
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;