name: Lançamento de Nova Versão

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Criar TAG de Lançamento
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config user.name "José Quintinno"
          git config user.email "josequintino@hotmail.com.br"

      - name: Obter última tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0.0")
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Renomear TAG
        id: bump
        run: |
          OLD_TAG=${{ env.TAG }}
          OLD_TAG=${OLD_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH BUILD <<< "$OLD_TAG"
          BUILD=$((BUILD + 1))
          NEW_TAG="v$MAJOR.$MINOR.$PATCH.$BUILD"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Atualizar versão no pom.xml
        run: |
          mvn versions:set -DnewVersion=${{ env.NEW_TAG }}
          mvn versions:commit

      - name: Commitar alteração da versão
        run: |
          git add pom.xml
          git commit -m "chore: atualiza versão do projeto para ${{ env.NEW_TAG }}"
          git push

      - name: Enviar TAG
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/${{ env.NEW_TAG }}$"; then
            echo "A tag ${{ env.NEW_TAG }} já existe no repositório remoto. Ignorando push."
          else
            git tag ${{ env.NEW_TAG }}
            git push origin ${{ env.NEW_TAG }}
          fi

      - name: Gerar Nova Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
