name: Lançamento de Nova Versão

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Criar TAG de Lançamento
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config user.name "Quintinno Digital"
          git config user.email "quintinno.com.br"

      - name: Obter última tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0.0")
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Renomear TAG
        id: bump
        run: |
          OLD_TAG=${{ env.TAG }}
          OLD_TAG=${OLD_TAG#v}
          IFS='.' read -r FEATURE HOTFIX BUGFIX BUG <<< "$OLD_TAG"
          BUG=$((BUG + 1))
          NEW_TAG="v1.$FEATURE.$HOTFIX.$BUG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Instalar xmlstarlet
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet

      - name: Atualizar versão no pom.xml com xmlstarlet
        run: |
          NEW_VERSION=${{ env.NEW_TAG }}
          NEW_VERSION=${NEW_VERSION#v}
          xmlstarlet ed -L -u "/project/version" -v "$NEW_VERSION" pom.xml
          git status
          cat pom.xml

      - name: Commitar alteração da versão se houver mudanças
        run: |
          git add pom.xml
          if git diff --cached --quiet; then
            echo "Nenhuma alteração para commitar."
          else
            git commit -m "release: Lançamento da Versão ${{ env.NEW_TAG }}"
            git push
          fi

      - name: Enviar TAG
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/${{ env.NEW_TAG }}$"; then
            echo "A tag ${{ env.NEW_TAG }} já existe no repositório remoto. Ignorando push."
          else
            git tag ${{ env.NEW_TAG }}
            git push origin ${{ env.NEW_TAG }}
          fi

      - name: Gerar Nova Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
